### ISSUE TITLE
Add api to set specific volume levels

### ISSUE THREAD

**Issue by VonOx** [jupe/onkyo.js#17]
### Description
- Type: Enhancement

## Enhancement

**There is no way to set specific volume ( only +1 or -1 )**

It could be usefull to set specific value

Thank you

**Comment by VonOx** [comment]
Error when trying `getVolume()`

```
Error: Command for 'AUDIO:STATUS' not defined
    at Promise.try (......\node_modules\onkyo.js\lib\Onkyo.js:540:15)
```

`setVolume()` is working fine

**Comment by jupe** [comment]
oh, thats true. My mistake. Here ia patch for it: 
https://github.com/jupe/onkyo.js/pull/23

**Comment by jupe** [comment]
actually there was typo in test which causes this bug leak.. anyway - patch is merged and should work now as expected.

**Comment by Codelica** [comment]
Thanks for the module. :)  Just a quick note that I think the hex volume string sent may need to be upper case.  At least in my case (with an Onkyo 818) volume commands that result in lowercase hex letters like "!1MVL1e" would fail.

Changing the volumeHex as follows fixed it:

`const volumeHex = volume.toString(16).toUpperCase();`

Thanks..

**Comment by jupe** [comment]
could you open new issue, or PR? Sounds like easy to fix, but I’ve to double check if it still works with my receiver..

**Comment by jupe** [comment]
I'll create new PR to fix uppercase issue, coming soon..

**Comment by jupe** [comment]
https://github.com/jupe/onkyo.js/releases/tag/v0.6.1

> Thanks for the module. :) Just a quick note that I think the hex volume string sent may need to be upper case. At least in my case (with an Onkyo 818) volume commands that result in lowercase hex letters like "!1MVL1e" would fail.

**Comment by Codelica** [comment]
Thanks for the speedy update! 👍
