### ISSUE TITLE
unknow_msgs

### ISSUE THREAD

**Issue by VonOx** [jupe/onkyo.js#28]
Just some unknow_msgs while testing

RX: unknown event: Error: Unknown data: DIM01
RX: unknown event: Error: Unknown data: RAS00
RX: unknown event: Error: Unrecognised key: SLI12

**Comment by jupe** [comment]
thank for reporting. I’ve not added all possible commands from Onkyo reference documentation so some might still missing. Its now very easy to add - just updating https://github.com/jupe/onkyo.js/blob/master/lib/onkyo.commands.js file and library generate API for it unless it needs parameters.. :). Any chance you to open PR for these? I can add more command support at next time I’ve time for this :)

**Comment by VonOx** [comment]
Yes of course, I will make a PR.

**Comment by jupe** [comment]
so dimmer with custom value (DIM01xx) is last missing part here, right?

**Comment by VonOx** [comment]
Yes you are right

**Comment by jupe** [comment]
https://michael.elsdoerfer.name/onkyo/ISCP_AVR_134.xlsx described that DIM01 does not parameters - so it's just similar than DIM02.. added it here: #30 .

**Comment by jupe** [comment]
DIM01 is now supported also.
