### ISSUE TITLE
onkyo.js available in Node-Red

### ISSUE THREAD

**Issue by djiwondee** [jupe/onkyo.js#33]
### Description
- Type: Question

## Question

Have you ever tried to embed this frame work into a node-red node? There are several example out there but none of it is really comfortable.

**Comment by jupe** [comment]
No I haven’t. I’m not familiar with node-red, but looks that it should be doable and perhaps rather easy..

**Comment by djiwondee** [comment]
Hello @jupe,

thanks for your reply. Does your answer imply you may have a look on that? your onkyo.js looks to me like the best maintained framework for EISCP with Onky receivers. The approaches available for integrating the AVRs for home automation are either less maintained, more complex to implement with additional layers/technoligical component on top or doesn't address the latest onkyo AVRs

**Comment by jupe** [comment]
I afraid that I dont have enough time to look at it more. Original idea was to provide just quality library that can be easily integrate to home automation projects which based on node.js. Anyway, there is tens of home automation framework options and onkyo support for each of them require a lot of study&effort. At the moment I don’t use node based home automation framework neither plan to start using some so no direct interest to implement integration either. Maybe in future. But sure I can help integration work that based on this library..
