### ISSUE TITLE
Additional commands

### ISSUE THREAD

**Issue by saxn-paule** [jupe/onkyo.js#8]
Have a look here for a lot of additional commands. Also for zone 2 and 3

https://github.com/saxn-paule/pimatic-onkyo-avr/blob/master/lib/onkyo.js/onkyo.commands.js

**Comment by jupe** [comment]
thanks - I added those missing groups to here: #3 :)

**Comment by jupe** [comment]
PR merged and will be included in next release. Please let me know if you would still want some changes :)
