### ISSUE TITLE
OnkyoDiscover class is not exposed

### ISSUE THREAD

**Issue by VonOx** [jupe/onkyo.js#9]
After ES6 Pr merged i have started my work ( Module for domotic software )

The discover function is not exposed and the exemple below is not working.

```javascript
const {OnkyoDiscover} = require('onkyo.js');
OnkyoDiscover.DiscoverFirst()
  .then((onkyo) => {
      return onkyo.powerOn();
  });
```
Error
```javascript
TypeError: Cannot read property 'DiscoverFirst' of undefined
```

Thank you

**Comment by jupe** [comment]
Thanks for raising this, maybe this line is the culprits: 
https://github.com/jupe/onkyo.js/blob/82c6ba79486d91feedb88a1b9f7b8538b6b51c11/package.json#L12

Probably it should be like:   `"main": "lib"`.
Will fix it asap..

**Comment by VonOx** [comment]
Yes that explain also why cli tool is not available too

**Comment by VonOx** [comment]
I confirm, fixed with `"main": "lib"`
